spring:
  mvc:
    path match:
      matching-strategy: ant_path_matcher
    hidden method:
      filter:
        enabled: true  #  open REST

  datasource:
    url: jdbc:mysql://localhost:3306/data_backup
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: abel
    password: 123456

  servlet:
    multipart:
      max-file-size: 50MB


server:
  port: 9999
